repos:
  # Python formatting
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.11
  
  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  
  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100", "--extend-ignore=E203"]
  
  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
  
  # Security
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-r", "domains/", "application/", "infrastructure/"]
  
  # Custom hooks
  - repo: local
    hooks:
      - id: validate-imports
        name: Validate import rules
        entry: python scripts/validate_imports.py
        language: system
        pass_filenames: false
      
      - id: check-domain-structure
        name: Check domain structure
        entry: python scripts/check_domain_structure.py
        language: system
        pass_filenames: false