version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: fluentpro_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fluentpro_celery_worker
    command: celery -A workers.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ..:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=fluentpro_backend.settings
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "celery", "-A", "workers.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fluentpro_celery_beat
    command: celery -A workers.celery_app beat --loglevel=info
    volumes:
      - ..:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=fluentpro_backend.settings
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  flower:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fluentpro_flower
    command: celery -A workers.celery_app flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - ..:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=fluentpro_backend.settings
      - FLOWER_BASIC_AUTH=admin:fluentpro123
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/api/workers"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: fluentpro_network